### ISSUE TITLE
Drop in replacement may fail in Django 1.7 with django.contrib.staticfiles

### ISSUE THREAD

**Issue by nealtodd** [dcramer/django-devserver#100]
In Django 1.7, if `django.contrib.staticfiles` is in `INSTALLED_APPS` and `django.contrib.staticfiles` comes before `devserver` in `INSTALLED_APPS` then staticfile's sub-classed runserver management command is used instead of django-devserver's runserver management command.

This breaks the drop-in replacement nature of devserver.

Putting `devserver` ahead of `django.contrib.staticfiles` results in django-devserver's runserver being used.

Might not be anything that can be done about that other than a note in the README about the ordering in `INSTALLED_APPS`.

**Comment by dukebody** [comment]
Wouldn't it be better to use a different command name like django_extensions do with runserver_plus? Something like "python manage.py devserver".

**Comment by x1024** [comment]
This has been the case for almost a year. Are you planning on shipping a version of devserver that works with the latest Django release?
