### ISSUE TITLE
Django 1.8.2 runserver not replaced

### ISSUE THREAD

**Issue by qlimax86** [dcramer/django-devserver#117]
Hi, sorry I have a problem with your application on Django 1.8.2/3.
when I run ./manage.py runserver, it doesn't take your command but the original one instead. 
I can't understand why.

I installed django-devserver with pip,

then in settings.py:

added 'devserver' to INSTALLED_APPS,
added 'devserver.middleware.DevServerMiddleware' to MIDDLEWARE_CLASSES
added some options:
DEVSERVER_DEFAULT_ADDR = '0.0.0.0'
DEVSERVER_DEFAULT_PORT = '8888'

when I run ./manage.py runserver it doesn't take the new address and port
and the help message suggests that it is the original runserver...

Any suggestion?
Thank You

**Comment by timtan** [comment]
MAYBE the order matter?

can you put devserver at the start of  INSTALLED_APPS?

**Comment by qlimax86** [comment]
Whoo, it works now!
So the guide is wrong as it says:

You will need to include devserver in your INSTALLED_APPS:
INSTALLED_APPS = (
    ...
    'devserver',
)

Thank you for your precious help!

**Comment by timtan** [comment]
my pleasure

**Comment by scottwoodall** [comment]
A little more information. For me it was making sure `devserver` came before `django.contrib.staticfiles` within `INSTALLED_APPS`. I didn't try and figure out why.

**Comment by arnists** [comment]
Are you adding modules?

DEVSERVER_MODULES = (
    'devserver.modules.sql.SQLRealTimeModule',
    'devserver.modules.sql.SQLSummaryModule',
    'devserver.modules.profile.ProfileSummaryModule',
    'devserver.modules.ajax.AjaxDumpModule',
    'devserver.modules.profile.MemoryUseModule',
    'devserver.modules.cache.CacheSummaryModule',
    'devserver.modules.profile.LineProfilerModule',
    'devserver.modules.sql.SQLRealTimeModule',
)

**Comment by qlimax86** [comment]
@arnists Yes
