### ISSUE TITLE
DEVSERVER_IGNORED_PREFIXES is ignored

### ISSUE THREAD

**Issue by arnists** [dcramer/django-devserver#118]
By default the devserver should not show output lines for static files or url prefixes defined in DEVSERVER_IGNORED_PREFIXES according to documentation.  This is my setup and results:

pip freeze:

Django==1.8.3
Werkzeug==0.10.4
argparse==1.2.1
click==4.0
django-devserver==0.8.0
doitlive==2.3.1
guppy==0.1.10
ipython==3.2.1
line-profiler==1.0
psycopg2==2.6.1
sqlparse==0.1.15
wsgiref==0.1.2

Relevant settings.py section:

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'devserver',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'devserver.middleware.DevServerMiddleware',
)

DEVSERVER_MODULES = (
    'devserver.modules.sql.SQLRealTimeModule',
    'devserver.modules.sql.SQLSummaryModule',
    'devserver.modules.profile.ProfileSummaryModule',
    'devserver.modules.ajax.AjaxDumpModule',
    'devserver.modules.profile.MemoryUseModule',
    'devserver.modules.cache.CacheSummaryModule',
    'devserver.modules.profile.LineProfilerModule',
    'devserver.modules.sql.SQLRealTimeModule',

)

DEVSERVER_TRUNCATE_SQL = False

DEVSERVER_IGNORED_PREFIXES = ['/static/',]

Sample output from python manage.py runserver:

Django version 1.8.3, using settings 'masterclass.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
    [sql] (11ms) 5 queries with 0 duplicates
    [profile] Total time to render was 0.22s
    [profile] 3.2 MB allocated, 26.8 KB deallocated, heap size is 20.4 MB
    [cache] 0 calls made with a 100% hit percentage (0 misses)
[15/Jul/2015 10:51:02]"GET /admin/auth/user/ HTTP/1.1" 200 6612
[15/Jul/2015 10:51:03]"GET /static/admin/css/base.css HTTP/1.1" 304 0
[15/Jul/2015 10:51:03]"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[15/Jul/2015 10:51:03]"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[15/Jul/2015 10:51:03]"GET /static/admin/js/core.js HTTP/1.1" 304 0
[15/Jul/2015 10:51:03]"GET /static/admin/js/jquery.js HTTP/1.1" 304 0
[15/Jul/2015 10:51:03]"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[15/Jul/2015 10:51:03]"GET /static/admin/js/actions.js HTTP/1.1" 304 0
[15/Jul/2015 10:51:03]"GET /static/admin/img/icon_searchbox.png HTTP/1.1" 304 0
[15/Jul/2015 10:51:03]"GET /static/admin/img/icon-yes.gif HTTP/1.1" 304 0
    [sql] (6ms) 2 queries with 0 duplicates
    [profile] Total time to render was 0.11s
    [profile] 128.7 KB allocated, 149.0 KB deallocated, heap size is 20.4 MB
    [cache] 0 calls made with a 100% hit percentage (0 misses)
[15/Jul/2015 10:51:03]"GET /admin/jsi18n/ HTTP/1.1" 200 2372

**Comment by Stekot** [comment]
I have the same issue, quick workaround is not to use {{ STATIC_URL }} in your html templates. Problem is that when you use {{ STATIC_URL }} request doesn't go trought the middleware.

**Comment by arnists** [comment]
Got a mail from a developer that had this same problem, don't know why s/he didn't post it here:

"""
I have the same issue, quick workaround is not to use {{ STATIC_URL }} in your html templates. Problem is that when you use {{ STATIC_URL }} request doesn't go throught the middleware.
"""

I was a bit embarrassed not to have thought of that.  Closing the issue (but adding to documentation would be nice)

**Comment by Stekot** [comment]
Reason why I deleted original comment was because after double check I found out it dosn't matter wheter you use {{ STATIC_URL }} or not. Static requests are not going through the middleware in both cases.

**Comment by arnists** [comment]
I just really wanted to understand why, your explanation was an epiphany
for me.  It's useful for others to realize the difference between the
devserver and runserver.  One is middleware, other is a core component.

**Comment by Stekot** [comment]
Still I would recommend to reopen the issue.

**Comment by arnists** [comment]
Yes, would be nice to see movement on the issue.  Devs seem focused
elsewhere.
